### ISSUE TITLE
I found 6 bugs

### ISSUE THREAD

**Issue by limafresh** [SarthakTools/PyEditor#1]
It looks stylish on the outside, but

**1. When you select text, copy it with Ctrl+C and paste it with Ctrl+V, it is pasted twice.**

![screenshot1](https://github.com/user-attachments/assets/f2b47286-ea12-4bcb-ae54-46db0eeb42c9)

**2. There is some kind of bug with the menu in Linux, that it is half empty, or even empty.**

It also can't be closed by clicking anywhere else on the screen, which is annoying. It closes if you click only on the menu title.

![screenshot2](https://github.com/user-attachments/assets/145c7f5d-ae2d-43a3-94fb-a24c1481aad6)

**3. There is no scrolling on the information page, everything is visible only if you expand the window, and when collapsed it looks ugly.**

![screenshot3](https://github.com/user-attachments/assets/cddfd765-100f-469c-ba16-3f0fbe98cbbc)

**4. I clicked "View Help", and there was a black window that wouldn't close, only exiting the entire program helped.**

![screenshot4](https://github.com/user-attachments/assets/995fe64f-8748-4431-8638-1731818639c3)

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/host/PyEditor/PyEditor/CTkScrollableDropdown/ctk_scrollable_dropdown.py", line 178, in <lambda>
    command=lambda k=row: self._attach_key_press(k), **button_kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/host/PyEditor/PyEditor/CTkScrollableDropdown/ctk_scrollable_dropdown.py", line 225, in _attach_key_press
    self.command(k)
  File "/home/host/PyEditor/PyEditor/main.py", line 225, in <lambda>
    justify="left", button_color="#080912", font=("monospace", 15), command=lambda e: select_option(e))
                                                                                      ^^^^^^^^^^^^^^^^
  File "/home/host/PyEditor/PyEditor/main.py", line 63, in select_option
    globals()[action]()
  File "/home/host/PyEditor/PyEditor/main.py", line 143, in view_help
    type_frame.grab_set()
  File "/usr/lib/python3.11/tkinter/__init__.py", line 963, in grab_set
    self.tk.call('grab', 'set', self._w)
_tkinter.TclError: grab failed: window not viewable
```

**5. Consider setting an icon in .png format.**

After all, .ico is only for Windows, and the application will not run on Linux and macOS unless you delete the line about the icon in the code.

**6. No license**

This means that others have no right to change and make their own versions of the application based on this, because if there is no license, then by default no one has the right to do this. Add a free license (for example MIT) - create a LICENSE file through the GitHub website and click the license selection button that appears and select a license.

**Comment by SarthakTools** [comment]
hello dude if u find error pls feel free to edit the code as i code on
windows .....

**Comment by limafresh** [comment]
Make this application open source software, adding a free license, and I will help.

**Comment by SarthakTools** [comment]
> Make this application open source software, adding a free license, and I will help.

Thanks u so much and pls don't make mess dude make sure it has no error.

**Comment by limafresh** [comment]
Will you add a license (for example MIT, GPL)? And I will help with development and bug fixing if you add it. After all, your project is not free software, and I don’t want to contribute in non-free software.

**Comment by SarthakTools** [comment]
brother i dont' have much knowledge about these license and all that i am
just a 17 years old programmer all id do is make programs and upload them
on github and YouTube ......
